// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web.Api.Infrastructure.Data.EntityFramework;

namespace Web.Api.Infrastructure.Migrations.AppDb
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-preview2-35157")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Web.Api.Infrastructure.Data.Entities.Aluno", b =>
                {
                    b.Property<int>("IdAluno")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdUsuario");

                    b.Property<int>("Ra");

                    b.HasKey("IdAluno");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Aluno");
                });

            modelBuilder.Entity("Web.Api.Infrastructure.Data.Entities.AlunoGrade", b =>
                {
                    b.Property<int>("IdAlunoGrade")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdAluno");

                    b.Property<int>("IdGrade");

                    b.HasKey("IdAlunoGrade");

                    b.HasIndex("IdGrade");

                    b.ToTable("AlunoGrade");
                });

            modelBuilder.Entity("Web.Api.Infrastructure.Data.Entities.Grade", b =>
                {
                    b.Property<int>("IdGrade")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdGradeDetalhe");

                    b.HasKey("IdGrade");

                    b.HasIndex("IdGradeDetalhe");

                    b.ToTable("Grade");
                });

            modelBuilder.Entity("Web.Api.Infrastructure.Data.Entities.GradeDetalhe", b =>
                {
                    b.Property<int>("IdGradeDetalhe")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CodGrade");

                    b.Property<string>("Curso");

                    b.Property<string>("Disciplina");

                    b.Property<int>("IdProfessor");

                    b.Property<string>("Turma");

                    b.HasKey("IdGradeDetalhe");

                    b.HasIndex("IdProfessor");

                    b.ToTable("GradeDetalhe");
                });

            modelBuilder.Entity("Web.Api.Infrastructure.Data.Entities.Professor", b =>
                {
                    b.Property<int>("IdProfessor")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Codigo");

                    b.Property<int>("IdUsuario");

                    b.HasKey("IdProfessor");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Professor");
                });

            modelBuilder.Entity("Web.Api.Infrastructure.Data.Entities.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cpf")
                        .IsRequired();

                    b.Property<string>("Email");

                    b.Property<string>("Login");

                    b.Property<string>("Nome");

                    b.Property<string>("Senha");

                    b.HasKey("IdUsuario");

                    b.HasAlternateKey("Cpf")
                        .HasName("AlternateKey_Cpf");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Web.Api.Infrastructure.Data.Entities.Aluno", b =>
                {
                    b.HasOne("Web.Api.Infrastructure.Data.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Web.Api.Infrastructure.Data.Entities.AlunoGrade", b =>
                {
                    b.HasOne("Web.Api.Infrastructure.Data.Entities.Grade", "Grade")
                        .WithMany()
                        .HasForeignKey("IdGrade")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Web.Api.Infrastructure.Data.Entities.Grade", b =>
                {
                    b.HasOne("Web.Api.Infrastructure.Data.Entities.GradeDetalhe", "GradeDetalhe")
                        .WithMany()
                        .HasForeignKey("IdGradeDetalhe")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Web.Api.Infrastructure.Data.Entities.GradeDetalhe", b =>
                {
                    b.HasOne("Web.Api.Infrastructure.Data.Entities.Professor", "Professor")
                        .WithMany()
                        .HasForeignKey("IdProfessor")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Web.Api.Infrastructure.Data.Entities.Professor", b =>
                {
                    b.HasOne("Web.Api.Infrastructure.Data.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
